repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
  - repo: local
    hooks:
      - id: tests
        name: run_tests
        entry: python tests/run_tests.py
        language: system
        types: [python]
        pass_filenames: false
